server:
  port: 10000

spring:
  application:
    name: oneCoupon-gateway
  cloud:
    nacos:
      discovery:
        enabled: false
    gateway:
      routes:
        - id: oneCoupon-merchant-admin
          uri: http://localhost:10010
          predicates:
            - Path=/api/merchant-admin/**

        - id: oneCoupon-user-goods
          uri: http://localhost:10010
          predicates:
            - Path=/api/user/**

        - id: oneCoupon-engine
          uri: http://localhost:10020
          predicates:
            - Path=/api/engine/**

        - id: oneCoupon-settlement
          uri: http://localhost:10030
          predicates:
            - Path=/api/settlement/**

        - id: oneCoupon-distribution
          uri: http://localhost:10040
          predicates:
            - Path=/api/distribution/**

        - id: oneCoupon-search
          uri: http://localhost:10050
          predicates:
            - Path=/api/search/**

jwt:
  secret: one-coupon-merchant-admin-jwt-secret-key-2026
  expiration: 86400000

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}
