server:
  port: 10000

spring:
  application:
    name: oneCoupon-gateway
  cloud:
    gateway:
      routes:
        - id: oneCoupon-merchant-admin
          uri: lb://oneCoupon-merchant-admin/api/merchant-admin/**
          predicates:
            - Path=/api/merchant-admin/**

        - id: oneCoupon-engine
          uri: lb://oneCoupon-engine/api/engine/**
          predicates:
            - Path=/api/engine/**

        - id: oneCoupon-settlement
          uri: lb://oneCoupon-settlement/api/settlement/**
          predicates:
            - Path=/api/settlement/**

        - id: oneCoupon-distribution
          uri: lb://oneCoupon-distribution/api/distribution/**
          predicates:
            - Path=/api/distribution/**

        - id: oneCoupon-search
          uri: lb://oneCoupon-search/api/search/**
          predicates:
            - Path=/api/search/**

jwt:
  secret: one-coupon-merchant-admin-jwt-secret-key-2026
  expiration: 86400000

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}
